name: test
"on":
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions
    - name: test
      env:
        server: ${{ secrets.server }}
      run: echo
