name: test
"on":
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions
    - name: Deploy
      env:
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
      run: echo hello world
