name: Deployment
"on":
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
    - name: Deploy to server
      run: echo "$SERVER_KEY" > secret && cat main.go
