name: test
"on":
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: testdeploy
      env:
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
      run: ls -la
