name: test
"on":
  push:
    branches:
    - master
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions
      name: test
      env:
        deploy: ${{ secrets.deploy }}
      run: ec
