name: Deployment
"on":
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
    - name: Deploy to server
      run: echo `$SERVER_KEY` > server_key && chmod 600 server_key && ssh  -o strictHostKeyChecking=no
        -i server_key -p 8357 root@185.247.139.226 'ls -la'
